import pygame, os, random
def update():
    pygame.display.flip()
pygame.init()
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
size = (800, 600)
font = pygame.font.SysFont('Calibri', 25, True, False)
screen = pygame.display.set_mode(size)
pygame.display.set_caption("HANGMAN")
clock = pygame.time.Clock()
screen.fill(WHITE)
clock.tick(60)
update()
#stage1 = pygame.image.load("stage1.png")
#screen.blit(stage1,(0,0))
#update()
file = open(os.getcwd() + "\\text.txt", 'r')
filetext = file.read().lower()
filetext = list(filetext.split())
#text = font.render(filetext, True, RED)
#screen.blit(text, [200, 200])
update()
def getRandomWord(wordList):
    wordIndex = random.randint(0, len(wordList) - 1)
    return wordList[wordIndex]
wordtest = getRandomWord(filetext)
wordtests = font.render(wordtest, True, RED)
for i in range(5):
    wordtest = getRandomWord(filetext)
    wordtests = font.render(wordtest, True, RED)
    screen.blit(wordtests, [random.randrange(0, 800), random.randrange(0, 600)])
    update()
    pygame.time.wait(100)
